params:
    
  no_epoch: 10000
  save_fre: 1000

  LR_1: 0.000001
  LR_2: 0.0001
  LR_3: 0.00001
  LR_4: 0.0000001



data:
  root_dir: "/home/kunet.ae/100053688/datastore/ViT-512"
  csv_dir: "/home/kunet.ae/100053688/datastore/csv-files/joined-data-512.csv"
  out_dir: "/home/kunet.ae/100053688/out/hpc_tasks_depth/trail_1/"
  batch_size: 8
  train_shuffle: True
  test_shuffle: False
  train_split:  0.7
  test_split:  0.3
  

hparams1:
  initial_image_size: 512
  n_heads: 16
  size: [256,128,64]
  dims: [3,4,16,64]
  patch_size: 16

hparams2:
  initial_image_size: 512
  n_heads: 16
  size:  [256,128,64]
  dims: [3,4,8,16]
  patch_size: 12

hparams3:
  initial_image_size: 512
  n_heads: 16
  size:  [256,128,64]
  dims: [3,4,8,16]
  patch_size: 12
    



hydra: 
 output_subdir: null  
 run:  
  dir: .  


