params:
  initial_image_size: 576
  n_heads: 12
  size: [288,144,72]
  dims: [3,4,16,64]
  patch_size: 12
data:
  root_dir:
  batch_size: 16
  shuffle: True

hydra:
  output_subdir: null













